### ISSUE TITLE
Error in installing pyspotify

### ISSUE THREAD

**Issue by psomdeb25** [richardk80/spotify-ripper#3]
I have installed libspotify and have also sym linked it to /Library/Frameworks/ directory however the pyspotify still fails.

Output of ls-l # Shows that libspotify exists
> total 0
> lrwxr-xr-x  1 root  admin  51 14 Jan 00:50 libspotify -> /Library/Frameworks/libspotify.framework/libspotify

pyspotify install error after pip install pyspotify:

>Collecting pyspotify
  Downloading pyspotify-2.1.3.tar.gz (157 kB)
     |████████████████████████████████| 157 kB 2.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Requirement already satisfied: setuptools in /Users/somdebpaul/opt/anaconda3/lib/python3.8/site-packages (from   pyspotify) (49.2.0.post20200714)
 Requirement already satisfied: cffi>=1.0.0 in /Users/somdebpaul/opt/anaconda3/lib/python3.8/site-packages (from pyspotify) (1.14.0)
 Requirement already satisfied: pycparser in /Users/somdebpaul/opt/anaconda3/lib/python3.8/site-packages (from cffi>=1.0.0->pyspotify) (2.20)
 Building wheels for collected packages: pyspotify
 Building wheel for pyspotify (pyproject.toml) ... error
 ERROR: Command errored out with exit status 1:
 command: /Users/somdebpaul/opt/anaconda3/bin/python /Users/somdebpaul/opt/anaconda3/lib/python3.8/site- packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/7h/z3vl3b7j1rng50m39zv12r2c0000gn/T/tmp9r_ivwvy
 cwd: /private/var/folders/7h/z3vl3b7j1rng50m39zv12r2c0000gn/T/pip-install-s0aea1tx/pyspotify_ca7eb089af7f4dc695d0b347b150d850
  Complete output (52 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/_spotify_build.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/link.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/user.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/social.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/config.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/version.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/compat.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/error.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/sink.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/track.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/playlist_unseen_tracks.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/session.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/offline.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/eventloop.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/album.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/artist.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/connection.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/playlist_track.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/playlist_container.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/utils.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/player.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/playlist.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/inbox.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/search.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/audio.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/toplist.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/image.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  running egg_info
  warning: no files found matching '*' under directory '.github'
  no previously-included directories found matching 'docs/_build'
  no previously-included directories found matching 'examples/tmp'
  warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
  writing manifest file 'pyspotify.egg-info/SOURCES.txt'
  copying spotify/api.h -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/api.processed.h -> build/lib.macosx-10.9-x86_64-3.8/spotify
  running build_ext
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/build
  creating build/temp.macosx-10.9-x86_64-3.8/build/temp.macosx-10.9-x86_64-3.8
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/somdebpaul/opt/anaconda3/include -arch x86_64 -I/Users/somdebpaul/opt/anaconda3/include -arch x86_64 -I/Users/somdebpaul/opt/anaconda3/include/python3.8 -c build/temp.macosx-10.9-x86_64-3.8/spotify._spotify.c -o build/temp.macosx-10.9-x86_64-3.8/build/temp.macosx-10.9-x86_64-3.8/spotify._spotify.o
  build/temp.macosx-10.9-x86_64-3.8/spotify._spotify.c:569:10: fatal error: 'libspotify/api.h' file not found
  #include "libspotify/api.h"
           ^~~~~~~~~~~~~~~~~~
   1 error generated.
   error: command '/usr/bin/gcc' failed with exit code 1
 
>  ERROR: Failed building wheel for pyspotify
>  Failed to build pyspotify
>  ERROR: Could not build wheels for pyspotify, which is required to install pyproject.toml-based projects

**Comment by richardk80** [comment]
Did you install using Python 2 or Python 3?
