### ISSUE TITLE
api.h / can't find pyspotify

### ISSUE THREAD

**Issue by jillburstein** [richardk80/spotify-ripper#5]
Hi there,

Struggling here with errors, re: not being able to find api.h (similar to what others have mentioned in forums), and can't find pyspotify. 

"pkg_resources.DistributionNotFound: The 'pyspotify==2.1.3' distribution was not found and is required by spotify-ripper"

Help?

Thanks!

**Comment by richardk80** [comment]
First off, what type of OS are you using? Are you using Python 2 or 3? Do you have pip installed?

**Comment by jillburstein** [comment]
Hi Richard,

Thanks so much for the reply. We did find someone to help us figure this
out. He had to  do something like to trick the OS into thinking it was
using Python 2. I can send you the steps he took if it would help others.
We were using Python 3 (most likely) and pip was installed, and yes, a Mac.

Best,
Jill
