### ISSUE TITLE
Program logs in, loads playlist and immediately logs out again

### ISSUE THREAD

**Issue by ricosuave73** [richardk80/spotify-ripper#6]
Trying to download a playlist, the output of spotify-ripper is this:

```
Logging in...
Logged in as [ID]
Loading playlist...
Loading playlist...
Logging out...
```
(replaced the true ID with [ID])

Input is as follows:

`spotify-ripper -u [USERNAME] -p [PASSWORD] -d /share/Multimedia/Music/Spotify -k PATH/TO/spotify_appkey.key spotify:user:[USER]:playlist:[PLAYLIST_ID]`

**Comment by richardk80** [comment]
Playlists don't work natively with this, and hasn't worked for a few years. If you want to download a playlist, you're going to have to put all of the track URIs into a text file, and then do it like this:

spotify-ripper -u [USERNAME] -p [PASSWORD] -d /share/Multimedia/Music/Spotify -k PATH/TO/spotify_appkey.key PATH/TO/playlist.txt
